default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: "postgres"
  password: "postgres"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vita_waller_api_development

test:
  <<: *default
  database: vita_waller_api_test

production:
  <<: *default
  database: vita_waller_api_production
  username: vita_waller_api
  password: <%= ENV["VITA_WALLER_API_DATABASE_PASSWORD"] %>
